runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:LIAQOEonH0tHSGr64Wv9cO3LCOjyg9I1GehkydKIHmM=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  # Set these environment variables according to your CloudSQL configuration.
  DB_HOST: 127.0.0.1
  DB_DATABASE: cspy
  DB_USERNAME: root
  DB_PASSWORD: snickers123
  DB_SOCKET: /cloudsql/codegeek-systems:us-central1:learn-cspy

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: /cloudsql/codegeek-systems:us-central1:learn-cspy
