runtime: php
env: flex

runtime_config:
  document_root: public

# Ensure we skip ".env", which is only for local development
skip_files:
  - .env

env_variables:
  # Put production environment variables here.
  APP_LOG: errorlog
  APP_KEY: base64:WqaHbR9YoHgaCz4TLjHa59264o1bG8JvnLZ/evJJjfM=
  STORAGE_DIR: /tmp
  CACHE_DRIVER: database
  SESSION_DRIVER: database
  # Set these environment variables according to your CloudSQL configuration.
  DB_HOST: localhost
  DB_DATABASE: cspy
  DB_USERNAME: root
  DB_PASSWORD: snickers123
  DB_SOCKET: /cloudsql/cspy-classroom:northamerica-northeast1:cspy

beta_settings:
    # for Cloud SQL, set this value to the Cloud SQL connection name,
    # e.g. "project:region:cloudsql-instance"
    cloud_sql_instances: cspy-classroom:northamerica-northeast1:cspy
